namespace Synthetix.Pipeline;

using System.Collections.Generic;
using System.Linq;
using Synthetix.Emit;
using Synthetix.Models;

/// <summary>
/// Stage 4 of the pipeline: it turns a finished <see cref="MapperPlan"/> into the
/// C# source text of the generated partial class.
/// </summary>
/// <remarks>
/// This stage does no thinking. Every value expression was already worked out by
/// Stage 3 and stored as a ready-made string, so the emitter only has to print
/// things in the right order with the right indentation. That is on purpose: a
/// "dumb" emitter is easy to read and easy to trust.
/// </remarks>
internal static class Emitter
{
    /// <summary>Builds the generated source file for one mapper.</summary>
    public static string Emit(MapperPlan plan)
    {
        var code = new SourceCodeBuilder();

        code.Line("// <auto-generated/> This file was produced by Synthetix. Do not edit it.");
        code.Line("#nullable enable");
        code.Line();

        bool hasNamespace = plan.Namespace.Length > 0;
        if (hasNamespace)
        {
            code.Line("namespace " + plan.Namespace);
            code.OpenBrace();
        }

        // Re-open any outer types the mapper is nested inside.
        foreach (ContainingType outer in plan.ContainingTypes)
        {
            code.Line("partial " + outer.Keyword + " " + outer.Name);
            code.OpenBrace();
        }

        // Re-open the mapper class itself and add the method bodies.
        string staticModifier = plan.IsStatic ? "static " : string.Empty;
        code.Line(plan.Accessibility + " " + staticModifier + "partial " + plan.TypeKeyword + " " + plan.Name);
        code.OpenBrace();

        bool firstMethod = true;
        foreach (MethodPlan method in plan.Methods)
        {
            if (!firstMethod)
            {
                code.Line();
            }

            firstMethod = false;
            EmitMethod(code, method);
        }

        // The collection helper methods come after the mapping methods.
        foreach (CollectionPlan helper in plan.CollectionHelpers)
        {
            code.Line();
            EmitCollectionHelper(code, helper, plan.IsStatic);
        }

        code.CloseBrace();

        // Close everything we opened, in reverse order.
        foreach (ContainingType _ in plan.ContainingTypes)
        {
            code.CloseBrace();
        }

        if (hasNamespace)
        {
            code.CloseBrace();
        }

        return code.ToString();
    }

    /// <summary>Writes one mapping method, signature and body.</summary>
    private static void EmitMethod(SourceCodeBuilder code, MethodPlan method)
    {
        // An IQueryable projection is a property, not a method - it has its own
        // expression-bodied shape (design doc 7.10).
        if (method.IsProjection)
        {
            EmitProjection(code, method);
            return;
        }

        string staticModifier = method.IsStatic ? "static " : string.Empty;

        // The "async" keyword is needed only when the body actually awaits
        // something. An async-shaped method whose values are all synchronous is
        // emitted without it and wraps its result in a completed task instead
        // (design doc 7.11). "async" must sit just before "partial".
        string asyncModifier = method.IsAsyncMethod && method.UsesAwait ? "async " : string.Empty;

        // An update method takes a second parameter - the target to fill.
        string parameters = method.IsUpdate
            ? method.SourceTypeDisplay + " " + method.SourceParameterName + ", " +
              method.TargetTypeDisplay + " " + method.TargetParameterName
            : method.SourceTypeDisplay + " " + method.SourceParameterName;

        // An async method may end with a CancellationToken parameter.
        if (method.CancellationTokenName.Length > 0)
        {
            parameters += ", global::System.Threading.CancellationToken " + method.CancellationTokenName;
        }

        code.Line(
            method.Accessibility + " " + staticModifier + asyncModifier + "partial " +
            method.ReturnTypeDisplay + " " + method.MethodName + "(" + parameters + ")");
        code.OpenBrace();

        if (method.IsPolymorphic)
        {
            EmitPolymorphicBody(code, method);
        }
        else if (method.HasValidBody)
        {
            EmitBody(code, method);
        }
        else
        {
            // Stage 3 could not build a real mapping. We still write a body so
            // the partial method has an implementation - otherwise the developer
            // would get a confusing extra compiler error on top of the clear
            // SYNTX error that explains the real problem.
            code.Line("// Synthetix could not generate this mapping. See the build error above for the reason.");
            code.Line("throw new global::System.NotImplementedException(" +
                      "\"Synthetix could not generate this mapping.\");");
        }

        code.CloseBrace();
    }

    /// <summary>
    /// Writes an IQueryable projection as an expression-bodied partial property
    /// (design doc 7.10): a single object-initializer lambda the consumer's
    /// compiler turns into an expression tree.
    /// </summary>
    private static void EmitProjection(SourceCodeBuilder code, MethodPlan method)
    {
        string staticModifier = method.IsStatic ? "static " : string.Empty;
        string signature = method.Accessibility + " " + staticModifier + "partial " +
                           method.ReturnTypeDisplay + " " + method.MethodName + " =>";

        code.Line(signature);

        if (method.HasValidBody)
        {
            // A "static" lambda guarantees the projection captures nothing.
            code.Line("    static " + method.SourceParameterName + " => " +
                      method.ProjectionBody + ";");
        }
        else
        {
            // Stage 3 raised SYNTX023. A throw keeps the partial property
            // satisfied, so the developer sees only the clear Synthetix error.
            code.Line("    throw new global::System.NotImplementedException(" +
                      "\"Synthetix could not generate this projection.\");");
        }
    }

    /// <summary>Writes the "build the target object and fill it in" body.</summary>
    private static void EmitBody(SourceCodeBuilder code, MethodPlan method)
    {
        // An update method assigns straight onto the existing target parameter -
        // no construction, no return (design doc 7.8).
        if (method.IsUpdate)
        {
            foreach (Assignment assignment in method.PostAssignments)
            {
                code.Line(method.TargetParameterName + "." + assignment.TargetName +
                          " = " + assignment.ValueExpression + ";");
            }

            return;
        }

        string constructorArguments = string.Join(
            ", ", method.ConstructorArguments.Select(argument => argument.ValueExpression));

        if (method.InitializerAssignments.Count > 0)
        {
            // Some members can only be set inside the "new T { ... }" initializer
            // (init-only or required members), so use that shape.
            code.Line("var target = new " + method.TargetTypeDisplay + "(" + constructorArguments + ")");
            code.OpenBrace();

            foreach (Assignment assignment in method.InitializerAssignments)
            {
                code.Line(assignment.TargetName + " = " + assignment.ValueExpression + ",");
            }

            code.CloseBrace(";");
        }
        else
        {
            code.Line("var target = new " + method.TargetTypeDisplay + "(" + constructorArguments + ");");
        }

        // Every remaining member is a plain "target.X = value;" line.
        foreach (Assignment assignment in method.PostAssignments)
        {
            code.Line("target." + assignment.TargetName + " = " + assignment.ValueExpression + ";");
        }

        code.Line(ReturnStatement(method, "target"));
    }

    /// <summary>
    /// Builds the "return ..." line for a mapping method. A plain method, and an
    /// async method that awaits something, both return the value directly - the
    /// "async" keyword wraps it. An async-shaped method that awaits nothing has
    /// no "async" keyword, so it must wrap the value in a completed task itself.
    /// </summary>
    private static string ReturnStatement(MethodPlan method, string value)
    {
        if (method.IsAsyncMethod && !method.UsesAwait)
        {
            return method.ReturnsValueTask
                ? "return new global::System.Threading.Tasks.ValueTask<" +
                  method.TargetTypeDisplay + ">(" + value + ");"
                : "return global::System.Threading.Tasks.Task.FromResult(" + value + ");";
        }

        return "return " + value + ";";
    }

    /// <summary>
    /// Writes the body of a polymorphic method: it checks the runtime type and
    /// hands off to the matching derived mapping (design doc 7.7).
    /// </summary>
    private static void EmitPolymorphicBody(SourceCodeBuilder code, MethodPlan method)
    {
        string parameter = method.SourceParameterName;

        // Exact-type checks, so a sub-subtype is never caught by its base's arm.
        code.Line("global::System.Type __runtimeType = " + parameter + ".GetType();");

        foreach (DerivedDispatch dispatch in method.DerivedDispatches)
        {
            code.Line(
                "if (__runtimeType == typeof(" + dispatch.SourceTypeDisplay + ")) return " +
                dispatch.MappingMethodName + "((" + dispatch.SourceTypeDisplay + ")" + parameter + ");");
        }

        code.Line(
            "throw new global::System.ArgumentException(\"Synthetix: " + method.MethodName +
            " has no mapping for runtime type '\" + __runtimeType + \"'.\");");
    }

    /// <summary>Writes one collection helper method (design doc 7.6).</summary>
    private static void EmitCollectionHelper(SourceCodeBuilder code, CollectionPlan helper, bool mapperIsStatic)
    {
        string modifier = mapperIsStatic ? "private static " : "private ";

        code.Line(
            modifier + helper.TargetTypeDisplay + " " + helper.MethodName +
            "(" + helper.SourceTypeDisplay + " source)");
        code.OpenBrace();

        if (helper.IsDictionary)
        {
            EmitDictionaryHelperBody(code, helper);
        }
        else
        {
            EmitSequenceHelperBody(code, helper);
        }

        code.CloseBrace();
    }

    /// <summary>Writes the body of an array / list / set / immutable-sequence helper.</summary>
    private static void EmitSequenceHelperBody(SourceCodeBuilder code, CollectionPlan helper)
    {
        const string immutable = "global::System.Collections.Immutable.";
        string element = helper.ElementTypeDisplay;

        // Construct the collection. The immutable kinds use a builder.
        switch (helper.TargetKind)
        {
            case CollectionKind.ImmutableArray:
                code.Line("var result = " + immutable + "ImmutableArray.CreateBuilder<" + element + ">();");
                break;
            case CollectionKind.ImmutableList:
                code.Line("var result = " + immutable + "ImmutableList.CreateBuilder<" + element + ">();");
                break;
            case CollectionKind.ImmutableHashSet:
                code.Line("var result = " + immutable + "ImmutableHashSet.CreateBuilder<" + element + ">();");
                break;
            default:
                code.Line("var result = new " + helper.ConcreteTargetTypeDisplay + "();");
                break;
        }

        // Map every element across.
        code.Line("foreach (var element in source)");
        code.OpenBrace();
        code.Line("result.Add(" + helper.ElementConversion + ");");
        code.CloseBrace();

        // Finish in the shape the target type needs.
        switch (helper.TargetKind)
        {
            case CollectionKind.Array:
                code.Line("return result.ToArray();");
                break;
            case CollectionKind.ImmutableArray:
            case CollectionKind.ImmutableList:
            case CollectionKind.ImmutableHashSet:
                code.Line("return result.ToImmutable();");
                break;
            default:
                code.Line("return result;");
                break;
        }
    }

    /// <summary>Writes the body of a dictionary helper.</summary>
    private static void EmitDictionaryHelperBody(SourceCodeBuilder code, CollectionPlan helper)
    {
        string key = helper.KeyTypeDisplay ?? "object";
        string value = helper.ElementTypeDisplay;

        if (helper.TargetKind == CollectionKind.ImmutableDictionary)
        {
            code.Line(
                "var result = global::System.Collections.Immutable.ImmutableDictionary.CreateBuilder<" +
                key + ", " + value + ">();");
        }
        else
        {
            code.Line("var result = new " + helper.ConcreteTargetTypeDisplay + "();");
        }

        code.Line("foreach (var pair in source)");
        code.OpenBrace();
        code.Line("result[" + helper.KeyConversion + "] = " + helper.ElementConversion + ";");
        code.CloseBrace();

        code.Line(helper.TargetKind == CollectionKind.ImmutableDictionary
            ? "return result.ToImmutable();"
            : "return result;");
    }

    /// <summary>
    /// Gathers every diagnostic in a plan - both the mapper-wide ones and the
    /// ones from each method - so the entry point can report them all.
    /// </summary>
    public static IEnumerable<DiagnosticInfo> CollectDiagnostics(MapperPlan plan)
    {
        foreach (DiagnosticInfo diagnostic in plan.MapperDiagnostics)
        {
            yield return diagnostic;
        }

        foreach (MethodPlan method in plan.Methods)
        {
            foreach (DiagnosticInfo diagnostic in method.Diagnostics)
            {
                yield return diagnostic;
            }
        }
    }
}
