namespace Synthetix.Manifest;

using System.Text;
using Synthetix.Models;

/// <summary>
/// Builds the manifest "carrier" file - a generated C# file that holds the
/// mapping manifest as plain comments.
/// </summary>
/// <remarks>
/// A source generator is only allowed to add C# source to a build; it may not
/// write its own files to disk (design doc 7.5). So Synthetix puts the manifest
/// text inside a comment-only .cs file. A normal build just compiles those
/// harmless comments. When the developer runs
/// "dotnet build -t:SynthetixUpdateManifest", the bundled MSBuild task reads
/// this carrier and copies the text out into the readable mapping/ files.
/// </remarks>
internal static class ManifestCarrierEmitter
{
    // These exact marker lines are also looked for by the MSBuild task in
    // Synthetix.targets. The two must always agree.
    private const string BeginMarker = "//SYNTHETIX-MANIFEST-BEGIN";
    private const string EndMarker = "//SYNTHETIX-MANIFEST-END";

    /// <summary>Builds the carrier file content for one mapper.</summary>
    public static string Emit(MapperPlan plan)
    {
        var file = new StringBuilder();

        file.Append("// <auto-generated/> Synthetix manifest carrier for ").Append(plan.Name).Append(".\n");
        file.Append("// It stores the mapping manifest as comments so the 'SynthetixUpdateManifest'\n");
        file.Append("// build target can write the readable mapping/ files. It has no executable code.\n");

        AppendBlock(file, plan.Name, "json", ManifestBuilder.BuildJson(plan));
        AppendBlock(file, plan.Name, "md", ManifestBuilder.BuildMarkdown(plan));

        return file.ToString();
    }

    /// <summary>Writes one BEGIN..END block with every content line prefixed by "//".</summary>
    private static void AppendBlock(StringBuilder file, string mapperName, string format, string content)
    {
        file.Append(BeginMarker).Append(" name=").Append(mapperName)
            .Append(" format=").Append(format).Append('\n');

        // Prefix every line with "//" so the whole block is a valid C# comment.
        foreach (string line in content.Replace("\r\n", "\n").Split('\n'))
        {
            file.Append("//").Append(line).Append('\n');
        }

        file.Append(EndMarker).Append('\n');
    }
}
