namespace Synthetix.Manifest;

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Synthetix.Models;

/// <summary>
/// Builds the mapping manifest for a mapper - the auditable, drift-checked record
/// of every mapping decision (design doc 7.5).
/// </summary>
/// <remarks>
/// The manifest is produced in two shapes:
/// a JSON file, which is exact and is what the drift check compares; and
/// a Markdown file, which is for people to read in a pull request.
/// Both are built here from the finished <see cref="MapperPlan"/>.
/// </remarks>
internal static class ManifestBuilder
{
    /// <summary>
    /// Builds the JSON manifest. The output is deterministic - the same plan
    /// always gives the exact same text - so it can be compared for drift.
    /// </summary>
    public static string BuildJson(MapperPlan plan)
    {
        var json = new StringBuilder();

        json.Append("{\n");
        json.Append("  \"mapper\": ").Append(JsonString(plan.Name)).Append(",\n");
        json.Append("  \"methods\": [");

        for (int m = 0; m < plan.Methods.Count; m++)
        {
            MethodPlan method = plan.Methods[m];
            json.Append(m == 0 ? "\n" : ",\n");
            AppendMethodJson(json, method);
        }

        json.Append(plan.Methods.Count > 0 ? "  ]\n" : "]\n");
        json.Append("}\n");
        return json.ToString();
    }

    private static void AppendMethodJson(StringBuilder json, MethodPlan method)
    {
        json.Append("    {\n");
        json.Append("      \"name\": ").Append(JsonString(method.MethodName)).Append(",\n");
        json.Append("      \"source\": ").Append(JsonString(method.SourceTypeDisplay)).Append(",\n");
        json.Append("      \"target\": ").Append(JsonString(method.TargetTypeDisplay)).Append(",\n");

        json.Append("      \"coverage\": { \"mapped\": ").Append(method.CoverageMapped)
            .Append(", \"ignored\": ").Append(method.CoverageIgnored)
            .Append(", \"unmapped\": ").Append(method.CoverageUnmapped).Append(" },\n");

        // Every mapping decision, in a stable order.
        List<Assignment> mappings = AllAssignments(method);
        json.Append("      \"mappings\": [");
        for (int i = 0; i < mappings.Count; i++)
        {
            json.Append(i == 0 ? "\n" : ",\n");
            json.Append("        { \"target\": ").Append(JsonString(mappings[i].TargetName))
                .Append(", \"source\": ").Append(JsonString(mappings[i].SourceDescription))
                .Append(", \"rule\": ").Append(JsonString(RuleText(mappings[i].Rule))).Append(" }");
        }

        json.Append(mappings.Count > 0 ? "\n      ],\n" : "],\n");

        AppendIgnoredJson(json, "ignoredTargets", method.IgnoredTargets, last: false);
        AppendIgnoredJson(json, "ignoredSources", method.IgnoredSources, last: true);

        json.Append("    }");
    }

    private static void AppendIgnoredJson(
        StringBuilder json, string field, EquatableArray<IgnoredMember> items, bool last)
    {
        json.Append("      \"").Append(field).Append("\": [");
        for (int i = 0; i < items.Count; i++)
        {
            json.Append(i == 0 ? "\n" : ",\n");
            json.Append("        { \"name\": ").Append(JsonString(items[i].Name))
                .Append(", \"reason\": ").Append(JsonString(items[i].Reason)).Append(" }");
        }

        json.Append(items.Count > 0 ? "\n      ]" : "]");
        json.Append(last ? "\n" : ",\n");
    }

    /// <summary>Builds the human-readable Markdown manifest.</summary>
    public static string BuildMarkdown(MapperPlan plan)
    {
        var md = new StringBuilder();

        md.Append("# Mapping manifest - ").Append(plan.Name).Append("\n\n");
        md.Append("_Generated by Synthetix. Run `dotnet build -t:SynthetixUpdateManifest` to refresh._\n");

        foreach (MethodPlan method in plan.Methods)
        {
            int required = method.CoverageMapped + method.CoverageUnmapped;

            md.Append("\n## ").Append(Short(method.TargetTypeDisplay)).Append(' ')
              .Append(method.MethodName).Append('(')
              .Append(Short(method.SourceTypeDisplay)).Append(' ')
              .Append(method.SourceParameterName).Append(")\n\n");

            md.Append("**Coverage:** ").Append(method.CoverageMapped).Append(" / ")
              .Append(required).Append(" target members");
            if (method.CoverageIgnored > 0)
            {
                md.Append(" (").Append(method.CoverageIgnored).Append(" ignored)");
            }

            md.Append("\n\n");

            AppendMarkdownTable(md, AllAssignments(method));

            foreach (IgnoredMember ignored in method.IgnoredTargets)
            {
                md.Append("\nIgnored - target: ").Append(ignored.Name)
                  .Append("  (").Append(ignored.Reason).Append(")\n");
            }

            foreach (IgnoredMember ignored in method.IgnoredSources)
            {
                md.Append("\nIgnored - source: ").Append(ignored.Name)
                  .Append("  (").Append(ignored.Reason).Append(")\n");
            }
        }

        return md.ToString();
    }

    /// <summary>Writes one Markdown table with the columns lined up neatly.</summary>
    private static void AppendMarkdownTable(StringBuilder md, List<Assignment> mappings)
    {
        if (mappings.Count == 0)
        {
            md.Append("_No members were mapped._\n");
            return;
        }

        // Work out how wide each column needs to be so the table looks tidy.
        int targetWidth = Max("Target".Length, mappings.Select(a => a.TargetName.Length));
        int sourceWidth = Max("Source".Length, mappings.Select(a => a.SourceDescription.Length));
        int ruleWidth = Max("Rule".Length, mappings.Select(a => RuleText(a.Rule).Length));

        md.Append("| ").Append(Pad("Target", targetWidth))
          .Append(" | ").Append(Pad("Source", sourceWidth))
          .Append(" | ").Append(Pad("Rule", ruleWidth)).Append(" |\n");

        md.Append("|").Append(Dashes(targetWidth + 2))
          .Append('|').Append(Dashes(sourceWidth + 2))
          .Append('|').Append(Dashes(ruleWidth + 2)).Append("|\n");

        foreach (Assignment mapping in mappings)
        {
            md.Append("| ").Append(Pad(mapping.TargetName, targetWidth))
              .Append(" | ").Append(Pad(mapping.SourceDescription, sourceWidth))
              .Append(" | ").Append(Pad(RuleText(mapping.Rule), ruleWidth)).Append(" |\n");
        }
    }

    // ===================== small shared helpers =====================

    /// <summary>Collects all of a method's mapping decisions in one stable order.</summary>
    private static List<Assignment> AllAssignments(MethodPlan method)
    {
        // A polymorphic method has no member assignments - its decisions are the
        // runtime-type dispatch arms instead.
        if (method.IsPolymorphic)
        {
            return method.DerivedDispatches
                .Select(dispatch => new Assignment(
                    Short(dispatch.SourceTypeDisplay),
                    dispatch.MappingMethodName + "(...)",
                    MappingRuleKind.PolymorphicDispatch,
                    "runtime type " + Short(dispatch.SourceTypeDisplay)))
                .ToList();
        }

        var all = new List<Assignment>();
        all.AddRange(method.ConstructorArguments);
        all.AddRange(method.InitializerAssignments);
        all.AddRange(method.PostAssignments);
        return all;
    }

    /// <summary>Turns a rule value into the short text shown in the manifest.</summary>
    private static string RuleText(MappingRuleKind rule) => rule switch
    {
        MappingRuleKind.SameName => "same-name",
        MappingRuleKind.FlattenPath => "flatten path",
        MappingRuleKind.UnflattenPath => "unflatten path",
        MappingRuleKind.MapProperty => "[MapProperty]",
        MappingRuleKind.Converter => "[MapProperty Use]",
        MappingRuleKind.ConstantValue => "[MapValue]",
        MappingRuleKind.ValueMethod => "[MapValue Use]",
        MappingRuleKind.UserMapping => "user mapping",
        MappingRuleKind.NestedMapping => "nested mapping",
        MappingRuleKind.ConstructorParameter => "constructor",
        MappingRuleKind.CollectionMapping => "collection",
        MappingRuleKind.PolymorphicDispatch => "derived-type dispatch",
        _ => "unknown",
    };

    /// <summary>Drops the "global::" prefix so Markdown headings read cleanly.</summary>
    private static string Short(string typeName)
        => typeName.StartsWith("global::", System.StringComparison.Ordinal)
            ? typeName.Substring("global::".Length)
            : typeName;

    /// <summary>Escapes a string so it is valid inside JSON, wrapped in quotes.</summary>
    private static string JsonString(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');

        foreach (char c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < ' ')
                    {
                        sb.Append("\\u").Append(((int)c).ToString("x4"));
                    }
                    else
                    {
                        sb.Append(c);
                    }

                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }

    private static int Max(int first, IEnumerable<int> rest)
    {
        int max = first;
        foreach (int value in rest)
        {
            if (value > max)
            {
                max = value;
            }
        }

        return max;
    }

    private static string Pad(string text, int width) => text.PadRight(width);

    private static string Dashes(int count) => new('-', count);
}
